controller:
  ingressClass: "tailscale"

  ingressClassResource:
    name: "tailscale"

  extraContainers:
    - name: tailscale-ingress
      image: host.k3d.internal:15555/tailscale-image:latest
      imagePullPolicy: Always
      volumeMounts:
      - mountPath: /opt/tailscale/
        name: opt-tailscale

  extraVolumes:
    - name: opt-tailscale
      hostPath:
        path: /opt/tailscale/
        type: DirectoryOrCreate