apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale-ingress-controller-rbac
  namespace: tailscale
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tailscale-ingress-controller-rbac
subjects:
- kind: ServiceAccount
  name: nginx-ingress-ingress-nginx
  namespace: tailscale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale-ingress-controller-rbac
  namespace: tailscale
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - patch

