ingress-nginx:
  controller:
    ingressClass: "tailscale"

    ingressClassResource:
      name: "tailscale"

    publishService:
      enabled: true

    service:
      type: NodePort

    extraContainers:
      - name: tailscale-ingress
        image: pthomison/tailscale-ingress-controller:b01957a
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /opt/tailscale/
          name: opt-tailscale

    extraVolumes:
      - name: opt-tailscale
        hostPath:
          path: /opt/tailscale/
          type: DirectoryOrCreate