apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-path
  volumeMode: Filesystem