name: Release Chart

on:  
  push:
    tags:
      - "*.*.*"

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.4.0
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
