name: Release Chart

on:
  push:
    tags:
      - "*.*.*"

    branches: [ main ]

  workflow_dispatch: {}

jobs:
  release_chart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.4.0
      with:
        charts_dir: "."
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
